# SPDX-License-Identifier: GPL-2.0
cdc-y := cdc_drv.o \
	 cdc_kms.o \
	 cdc_crtc.o \
	 cdc_plane.o \
	 cdc_lvdscon.o \
	 cdc_encoder.o \
	 cdc_hw.o \
	 cdc_hw_helpers.o \
	 cdc_deswizzle.o

obj-$(CONFIG_DRM_TES_CDC) += cdc.o
